/* FLIPLOT: persistent bank, conversations and in-person trades. */
(()=>{
const H=3600000,D=24*H;
const c=state.commerce=Object.assign({version:1,bank:null,balance:0,transactions:[],favorites:[],chats:{},inventory:[]},state.commerce||{});
let bankOpen=false,meetingId=null,bankTimer=null,npcStamp='';
const itemBy=id=>CATALOG.items.find(i=>i.id===id);
const purchased=id=>c.inventory.some(x=>x.id===id);
const btn=(a,t,extra='')=>`<button type="button" data-trade="${a}" ${extra}>${t}</button>`;
const when=t=>new Date(t).toLocaleString('ru-RU',{timeZone:'UTC',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'});
const portrait=s=>{const n=CATALOG.sellers.findIndex(x=>x.id===s.id);return `<span class="npc-portrait" role="img" aria-label="${html(s.appearance)}" style="background-position:${n%5*25}% ${Math.floor(n/5)*50}%"></span>`};
const voices={danya:['Привет!','Да, без проблем.','Не, так совсем дёшево.'],artem:['Здравствуйте.','Договорились.','Ниже пока не готов.'],kirill:['Привет!','Хорошо, меня устраивает.','За такую сумму не получится.'],max:['Здорово.','Ладно, забирай.','За столько не отдам.'],ruslan:['Добрый день.','По рукам.','Цена и так адекватная.'],timur:['Привет!','Окей, договорились.','Слишком низко, дружище.'],ilya:['Здравствуйте.','Да, устроит.','Нет, это маловато.'],sergey:['Здорово.','Лады, сойдёмся.','Не, за копейки не отдам.'],viktor:['Добрый день.','Хорошо, условились.','Уступить могу, но не столько.'],lera:['Привет :)','Окей, забирай!','Не-а, это уже слишком мало :)'],nastya:['Здравствуйте!','Отлично, договорились.','Спасибо за предложение, но это мало.'],alina:['Привет!','Да, подходит.','Пока так сильно не уступлю.'],olya:['Здравствуйте!','Хорошо, пусть будет так.','Нет, хотелось бы побольше.'],marina:['Добрый день!','Хорошо, отдаю за эту сумму.','Извините, дешевле пока не могу.'],nina:['Здравствуй, дорогой человек.','Хорошо, пусть тебе послужит.','Ох, это совсем мало. Давай чуть побольше.']};
function say(s,type,tail=''){return voices[s.id][type]+' '+tail}
function chatFor(id){if(!c.chats[id]){const i=itemBy(id),s=sellerFor(i.sellerId);c.chats[id]={price:i.price,messages:[{who:'seller',text:say(s,0,`По объявлению «${i.title}» — спрашивай, вещь пока у меня.`)}],asked:[],attempts:0,appointment:null,checks:[],discounted:false};save()}return c.chats[id]}
function message(ch,who,text){ch.messages.push({who,text});save()}
function ready(){return !!c.bank?.funded}
function tutorial(){const lock=state.phoneOwned&&!ready();$('phone-dock').classList.toggle('bank-tutorial',lock);document.querySelectorAll('.phone-app').forEach(b=>{b.disabled=lock&&b.dataset.app!=='Банк'});if($('phone-notice')&&($('phone-notice').textContent.startsWith('Сначала открой Банк')||lock))$('phone-notice').textContent='';}
const bankButton=document.createElement('button');bankButton.className='phone-app';bankButton.dataset.app='Банк';bankButton.innerHTML='<span class="app-icon">₽</span>Банк';document.querySelector('.phone-apps').append(bankButton);
const bank=document.createElement('section');bank.id='bank-app';bank.hidden=true;bank.setAttribute('role','dialog');bank.setAttribute('aria-label','Игровой банк');document.querySelector('.phone-screen').append(bank);
const npcs=document.createElement('div');npcs.id='meeting-npcs';$('stage').append(npcs);
const scene=document.createElement('section');scene.id='trade-scene';scene.hidden=true;scene.setAttribute('role','dialog');scene.setAttribute('aria-modal','true');scene.setAttribute('aria-label','Встреча с продавцом');$('stage').append(scene);
function grant(){if(!c.bank||c.bank.funded)return;c.bank.funded=true;c.balance+=5000;c.transactions.push({id:'family-gift',amount:5000,name:'Родственники',time:state.time});save();tutorial();if(bankOpen)renderBank()}
function scheduleGrant(){clearTimeout(bankTimer);if(c.bank&&!c.bank.funded)bankTimer=setTimeout(grant,Math.max(0,c.bank.giftDue-Date.now()))}
function renderBank(){const b=c.bank;bank.innerHTML=`<header><b>БАНК <small>FLIP</small></b>${ready()?btn('bank-close','×','aria-label="Закрыть банк"'):''}</header>`+(!b?`<form id="card-form"><h2>Оформление карты</h2><p class="bank-lead">Заполни данные владельца</p><div class="bank-form-grid"><label>Имя<input name="first" maxlength="30" required value="${html(playerName())}" autocomplete="off"></label><label>Фамилия<input name="surname" maxlength="40" required autocomplete="off"></label><label>Возраст<input name="age" type="number" min="14" max="100" required></label></div><fieldset><legend>Дизайн карты</legend><div class="design-row"><label><input type="radio" name="design" value="mint" checked> Мята</label><label><input type="radio" name="design" value="night"> Ночь</label><label><input type="radio" name="design" value="sunset"> Закат</label></div></fieldset><button type="submit">Оформить карту</button><p id="bank-error" role="alert"></p></form>`:`<div class="bank-card ${b.design}"><small>FLIP · дебетовая</small><strong>${money(c.balance)}</strong><span>•••• 0816</span><b>${html(b.first)} ${html(b.surname)}</b></div><p class="bank-status" role="status">${b.funded?'Карта готова к покупкам':'Карта оформлена. Ожидаем первый перевод…'}</p><h3>История платежей</h3>${c.transactions.slice().reverse().map(t=>`<div class="bank-transaction"><span>${html(t.name)}<small>${when(t.time)}</small></span><b class="${t.amount>0?'income':''}">${t.amount>0?'+':''}${money(t.amount)}</b></div>`).join('')||'<p>Операций пока нет</p>'}`);
const f=$('card-form');if(f)f.onsubmit=e=>{e.preventDefault();const data=new FormData(f),first=data.get('first').trim(),surname=data.get('surname').trim(),age=Number(data.get('age'));if(!first||!surname||!Number.isInteger(age)||age<14||age>100){$('bank-error').textContent='Заполни имя, фамилию и возраст от 14 до 100.';return}c.bank={first,surname,age,design:data.get('design'),funded:false,giftDue:Date.now()+3000};save();renderBank();scheduleGrant()}}
function openBank(){if(!state.phoneOwned||state.location==='map')return;closeMarket(true);setPhoneOpen(true);bankOpen=true;bank.hidden=false;$('phone-dock').classList.add('bank-mode');renderBank();bank.querySelector('input,button')?.focus()}
function closeBank(){if(!ready())return;bankOpen=false;bank.hidden=true;$('phone-dock').classList.remove('bank-mode');last=performance.now();bankButton.focus()}
bank.onclick=e=>{if(e.target.closest('[data-trade="bank-close"]'))closeBank()};bankButton.onclick=openBank;
const originalOpenMarket=openMarket;openMarket=function(view){if(!ready()){openBank();return}closeBank();originalOpenMarket(view)};
const originalPhone=setPhoneOpen;setPhoneOpen=function(open){if(bankOpen&&!ready()&&!open)return;originalPhone(open);tutorial()};
const originalAdvance=advance;advance=function(ms){if(bankOpen||meetingId)return;originalAdvance(ms)};
const originalGo=go;go=function(id){if(meetingId||bankOpen)return;originalGo(id)};
const originalRender=render;render=function(){originalRender();renderNPCs();tutorial()};
const originalFilter=filteredItems;filteredItems=function(){return originalFilter().filter(i=>!purchased(i.id))};
const originalView=showMarketView;showMarketView=function(view,push=true){originalView(view,push);const p=$('market-page');if(view.type==='item'){const i=itemBy(view.id);p.querySelector('.detail-copy').insertAdjacentHTML('beforeend',`<div class="trade-actions">${purchased(i.id)?'<b>Уже куплено · в твоих вещах</b>':btn('write','Написать')}${btn('favorite',c.favorites.includes(i.id)?'♥ В избранном':'♡ В избранное')}</div>`)}if(view.type==='seller'&&view.tab!=='reviews'){p.querySelectorAll('[data-item]').forEach(b=>{if(purchased(b.dataset.item))b.remove()});const tab=p.querySelector('[data-tab=ads]');if(tab)tab.textContent='Объявления · '+CATALOG.items.filter(i=>i.sellerId===view.id&&!purchased(i.id)).length}if(['chat','favorites','inbox','inventory'].includes(view.type))renderExtra(view)};
function renderExtra(view){const p=$('market-page');let out=btn('back','← Назад');if(view.type==='favorites')out+='<h2>Избранное</h2><div class="listing-grid">'+CATALOG.items.filter(i=>c.favorites.includes(i.id)).map(listingCard).join('')+'</div>'+(c.favorites.length?'':'<p>Сохраняй понравившиеся объявления сердечком.</p>');if(view.type==='inventory')out+='<h2>Мои покупки</h2><div class="listing-grid">'+c.inventory.map(x=>listingCard(itemBy(x.id))).join('')+'</div>'+(c.inventory.length?'':'<p>Здесь появятся вещи после встречи и оплаты.</p>');if(view.type==='inbox')out+='<h2>Сообщения и встречи</h2>'+Object.entries(c.chats).map(([id,ch])=>`<button class="inbox-row" data-chat="${id}">${portrait(sellerFor(itemBy(id).sellerId))}<span><b>${html(sellerFor(itemBy(id).sellerId).name)} · ${html(itemBy(id).title)}</b><small>${html(ch.messages.at(-1).text)}</small></span></button>`).join('')+(Object.keys(c.chats).length?'':'<p>Нажми «Написать» в объявлении.</p>');if(view.type==='chat'){const i=itemBy(view.id),s=sellerFor(i.sellerId),ch=chatFor(i.id),a=ch.appointment;out+=`<div class="chat-heading">${portrait(s)}<span><b>${html(s.name)}</b><small>${html(i.title)} · ${money(ch.price)}</small></span></div><div class="chat-messages">${ch.messages.map(m=>`<p class="bubble ${m.who}">${html(m.text)}</p>`).join('')}</div>`;
if(purchased(i.id))out+='<p class="success">Сделка завершена. Вещь в твоих покупках.</p>';else if(a?.status==='confirmed')out+=`<div class="appointment"><b>Встреча: ${when(a.time)}</b><p>${html(ASSETS[a.location].name)} · ${html(a.spot)}<br>Продавец будет с ${when(a.time-H)} до ${when(a.time+H)}.</p>${state.time>a.time+H?btn('reschedule','Встреча пропущена — перенести'):btn('cancel','Отменить встречу')}</div>`;else if(a?.status==='proposed')out+=`<div class="trade-actions">${btn('confirm','Подходит, договорились')}${btn('later','Другое время')}${btn('cancel','Пока не готов')}</div>`;else out+=`<div class="quick-phrases">${!ch.asked.includes('condition')?btn('condition','Какое состояние?'):''}${!ch.asked.includes('reason')?btn('reason','Почему продаёте?'):''}${!ch.asked.includes('auth')?btn('auth','Есть бирка / маркировка?'):''}</div><form id="offer-form"><label>Предложить цену, ₽<input id="offer-price" type="number" min="1" max="${ch.price}" step="1" required inputmode="numeric" placeholder="Твоя сумма"></label><button>Предложить</button></form><p id="offer-error" role="alert"></p>${ch.counter?btn('accept',`Согласиться на ${money(ch.counter)}`):''}${btn('buy',`Купить за ${money(ch.price)}`)}<small class="trade-note">Сначала договоримся о встрече. Оплата после осмотра.</small>`;}
p.innerHTML=out;const f=$('offer-form');if(f)f.onsubmit=e=>{e.preventDefault();trade('offer',Number($('offer-price').value))};p.querySelector('.chat-messages')?.scrollTo?.(0,999999)}
const spots={yard:'у подъезда, возле лавочки',park:'у центральной аллеи',garages:'у въезда в кооператив',mall:'у главного входа',pvz:'рядом со входом в пункт выдачи'};
function propose(i,ch,alternative=false){const s=sellerFor(i.sellerId),day=Math.floor(state.time/D)*D,idx=CATALOG.sellers.indexOf(s);let t=day+(12+idx%7)*H;if(t<state.time+H)t=Math.ceil((state.time+H)/H)*H;if(t>=day+21*H)t=day+D+(11+idx%7)*H;if(alternative){t=(ch.appointment?.time||t)+2*H;if(t>=day+21*H&&t<day+D)t=day+D+12*H;if(t>=day+2*D||t>day+D+20*H)t=day+D+12*H}ch.appointment={status:'proposed',time:t,location:s.location,spot:spots[s.location]};message(ch,'seller',(s.id==='nina'?'Давай встретимся, мне удобно ':'Мне удобно ')+when(t)+', '+ASSETS[s.location].name+', '+spots[s.location]+'. Подойдёт?')}
function trade(action,value){if(action==='back'){marketBack();return}const i=itemBy(marketView.id);if(!i)return;const ch=chatFor(i.id),s=sellerFor(i.sellerId);if(action==='favorite'){c.favorites=c.favorites.includes(i.id)?c.favorites.filter(x=>x!==i.id):[...c.favorites,i.id];save();showMarketView(marketView,false);return}if(action==='write'){showMarketView({type:'chat',id:i.id});return}if(purchased(i.id))return;
if(['condition','reason','auth'].includes(action)&&!ch.asked.includes(action)){ch.asked.push(action);const questions={condition:'Какое состояние? Есть недостатки?',reason:'Почему продаёте?',auth:'Есть бирка или маркировка? Можно проверить?'};message(ch,'you',questions[action]);const ans={condition:`По состоянию: ${i.condition.toLowerCase()}. ${s.id==='nina'?'Бережно хранила, на встрече посмотришь сам.':'На встрече можно спокойно всё осмотреть.'}`,reason:s.id==='nina'?'Дома лежит без дела. Пусть лучше кому-нибудь пригодится.':s.id==='lera'?'Меняю стиль, освобождаю шкаф :)':s.id==='kirill'?'Освобождаю место, хочу купить кое-что другое.':'Перестали пользоваться, поэтому продаю.',auth:s.id==='nina'?'Я в этих марках не очень разбираюсь. Посмотришь на месте, торопить не буду.':'Маркировку и состояние проверишь на встрече. Чека уже нет.'};message(ch,'seller',ans[action])}
if(action==='offer'){if(!Number.isSafeInteger(value)||value<1||value>ch.price){$('offer-error').textContent='Введи целую сумму от 1 до текущей цены.';return}message(ch,'you',`Отдадите за ${money(value)}?`);ch.attempts++;const floor=Math.round(i.price*(.78+(CATALOG.sellers.indexOf(s)%5)*.035)/50)*50;if(value>=floor){ch.price=value;ch.counter=null;message(ch,'seller',say(s,1,`Цена ${money(value)}.`))}else{ch.counter=ch.attempts>2?floor:Math.min(ch.price,Math.max(floor,Math.round((ch.price-(ch.price-floor)*.6)/50)*50));message(ch,'seller',say(s,2,`Могу предложить ${money(ch.counter)}. ${ch.attempts>2?'Это уже моя окончательная цена.':''}`));if(ch.attempts>2)ch.counter=floor}}
if(action==='accept'&&ch.counter){ch.price=ch.counter;ch.counter=null;message(ch,'you',`Договорились на ${money(ch.price)}.`);message(ch,'seller',say(s,1))}
if(action==='buy'||action==='reschedule'){message(ch,'you',`Хочу купить за ${money(ch.price)}. Когда встретимся?`);propose(i,ch)}if(action==='later'){message(ch,'you','Можно в другое время?');propose(i,ch,true)}if(action==='confirm'&&ch.appointment?.status==='proposed'){const a=ch.appointment;const overlap=Object.entries(c.chats).some(([id,x])=>id!==i.id&&x.appointment?.status==='confirmed'&&Math.abs(x.appointment.time-a.time)<H);if(overlap){message(ch,'seller','На это время у тебя уже есть встреча. Давай выберем другое.');propose(i,ch,true)}else{a.status='confirmed';message(ch,'you','Подходит, договорились.');message(ch,'seller',say(s,1,`Буду на месте за час до встречи, подожду до ${when(a.time+H)}.`))}}if(action==='cancel'){ch.appointment=null;message(ch,'you','Пока отменим встречу.');message(ch,'seller',say(s,1,'Если решишь — напиши.'))}save();renderExtra(marketView);npcStamp='';renderNPCs()}
$('market-app').addEventListener('click',e=>{const b=e.target.closest('[data-trade]');if(b)trade(b.dataset.trade);const ch=e.target.closest('[data-chat]');if(ch)showMarketView({type:'chat',id:ch.dataset.chat})});
for(const [type,label] of [['favorites','♡'],['inbox','Чаты'],['inventory','Покупки']]){const b=document.createElement('button');b.className='market-icon';b.textContent=label;b.setAttribute('aria-label',type==='favorites'?'Избранное':label);b.onclick=()=>showMarketView({type});$('market-close').before(b)}
function available(id){const a=c.chats[id]?.appointment;return !purchased(id)&&a?.status==='confirmed'&&a.location===state.location&&state.time>=a.time-H&&state.time<=a.time+H}
function renderNPCs(){const ids=Object.keys(c.chats).filter(available),key=state.location+ids.join();if(key===npcStamp)return;npcStamp=key;npcs.innerHTML=ids.map(id=>{const i=itemBy(id),s=sellerFor(i.sellerId);return `<button class="meeting-person" data-meet="${id}">${portrait(s)}<b>${html(s.name)}</b><small>${html(i.title)}</small></button>`}).join('')}
npcs.onclick=e=>{const b=e.target.closest('[data-meet]');if(!b||!available(b.dataset.meet)||titleOpen)return;meetingId=b.dataset.meet;document.body.classList.add('trade-active');setPhoneOpen(false);$('trade-scene').hidden=false;drawMeeting()};
function defect(i){if(i.condition==='Новое'||i.condition==='Как новое'||i.imageIndex%3!==0)return null;if(i.category==='Электроника')return {check:'function',text:'Левый канал тише правого.',line:'При проверке звук в одном наушнике тише.',discount:.25};if(i.imageIndex%2===0)return {check:'label',text:'Маркировка не совпадает с моделью. Есть признаки неоригинальной вещи.',line:'На бирке другая модель, маркировка не совпадает.',discount:.3};return {check:'wear',text:i.category==='Обувь'?'У подошвы расходится шов.':'Обнаружен расходящийся шов, которого не было видно на фото.',line:'Здесь расходится шов. Об этом не было в объявлении.',discount:.2}}
function drawMeeting(line=''){const i=itemBy(meetingId),s=sellerFor(i.sellerId),ch=chatFor(i.id),f=defect(i),found=f&&ch.checks.includes(f.check);scene.innerHTML=`<div class="novel-visual"><div class="novel-person">${portrait(s)}</div><div class="novel-product">${itemArt(i)}<span>${html(i.title)}</span></div></div><div class="novel-dialog"><div class="novel-title"><b>${html(s.name)}</b><span>${money(ch.price)} · у тебя ${money(c.balance)}</span></div><p aria-live="polite">${html(line||say(s,0,s.id==='nina'?'Вот, принесла. Посмотри внимательно, не торопись.':'Вот вещь. Осмотри, потом решишь.'))}</p>${found?`<p class="defect" role="alert">⚠ ${html(f.text)}</p>`:''}<div class="inspection-results">${ch.checks.map(k=>`<span class="${f?.check===k?'defect':'success'}">${({label:'Бирка / маркировка',wear:'Швы и износ',function:'Проверка в деле'})[k]}: ${f?.check===k?'есть проблема':'проверено'}</span>`).join('')}</div><div class="novel-choices">${!ch.checks.includes('label')?btn('inspect-label','Посмотреть бирку / маркировку'):''}${!ch.checks.includes('wear')?btn('inspect-wear','Проверить швы и износ'):''}${!ch.checks.includes('function')?btn('inspect-function',i.category==='Электроника'?'Проверить работу':'Рассмотреть и примерить'):''}${found&&!ch.discounted?btn('defect-bargain','Указать на недостаток и снизить цену'):''}${btn('pay',`Оплатить ${money(ch.price)}`,c.balance<ch.price?'disabled':'')}${btn('leave','Я ещё подумаю')}${btn('decline','Отказаться от покупки')}</div>${c.balance<ch.price?'<p class="defect">Недостаточно денег. Можно отказаться или вернуться позже.</p>':''}</div>`;scene.querySelector('button')?.focus()}
function endMeeting(){document.body.classList.remove('trade-active');meetingId=null;scene.hidden=true;last=performance.now();npcStamp='';renderNPCs();save()}
scene.onclick=e=>{const b=e.target.closest('[data-trade]');if(!b||!meetingId)return;const action=b.dataset.trade,i=itemBy(meetingId),ch=chatFor(i.id),s=sellerFor(i.sellerId),f=defect(i);if(action.startsWith('inspect-')){const check=action.slice(8);if(!ch.checks.includes(check))ch.checks.push(check);save();drawMeeting(f?.check===check?f.line:check==='label'?'Маркировка читается, несоответствий не найдено.':check==='wear'?'Состояние соответствует описанию. Дополнительных повреждений не видно.':'Проверка прошла нормально, всё соответствует описанию.');return}if(action==='defect-bargain'&&f&&ch.checks.includes(f.check)&&!ch.discounted){ch.discounted=true;ch.price=Math.max(1,Math.round(ch.price*(1-f.discount)/50)*50);message(ch,'you',f.line);const line=s.id==='nina'?`Ох, не заметила. Конечно, уступлю. Давай ${money(ch.price)}.`:`Да, вижу. Учтём недостаток: отдам за ${money(ch.price)}.`;message(ch,'seller',line);drawMeeting(line);return}if(action==='pay'){if(purchased(i.id)||!ready()||c.balance<ch.price||!available(i.id))return;c.balance-=ch.price;c.transactions.push({id:'purchase-'+i.id,amount:-ch.price,name:s.name+' · '+i.title,time:state.time});c.inventory.push({id:i.id,price:ch.price,time:state.time,checks:[...ch.checks],defect:ch.discounted?f?.text:null});ch.appointment.status='completed';message(ch,'seller',say(s,1,'Оплата пришла, вещь твоя!'));save();scene.innerHTML=`<div class="purchase-done">${itemArt(i)}<h2>Покупка твоя</h2><p>${html(i.title)} · ${money(ch.price)}</p><p>Остаток: ${money(c.balance)}</p>${btn('done','Забрать и продолжить')}</div>`;return}if(action==='decline'){ch.appointment=null;message(ch,'you','Спасибо, от покупки откажусь.');endMeeting()}if(action==='leave'||action==='done')endMeeting()};
document.addEventListener('keydown',e=>{if(!bankOpen&&!meetingId)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(meetingId)endMeeting();else closeBank()}if(e.key==='Tab'){const root=meetingId?scene:bank,buttons=[...root.querySelectorAll('button,input')].filter(x=>!x.disabled),a=buttons[0],b=buttons.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();b?.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a?.focus()}}},true);
window.gameDebug.advance=advance;window.gameDebug.go=go;
tutorial();scheduleGrant();renderNPCs();save();
})();
